// Shared chart colors and theme
const STATUS_COLORS = {
  "Critically Endangered": "#d1495b",
  Endangered: "#f08c2e",
  Vulnerable: "#d6b43f",
  Extinct: "#7b61d1",
  "Conservation Dependent": "#6f9f86",
  "Extinct in the wild": "#9a7bd8",
};

const STATUS_RANGE = [
  STATUS_COLORS["Critically Endangered"],
  STATUS_COLORS.Endangered,
  STATUS_COLORS.Vulnerable,
  STATUS_COLORS.Extinct,
];

const STATUS_RANGE_THREE = [
  STATUS_COLORS["Critically Endangered"],
  STATUS_COLORS.Endangered,
  STATUS_COLORS.Vulnerable,
];

const MAMMAL_COLOR = "#7fb39a";

const STATUS_ORDER = [
  "Critically Endangered",
  "Endangered",
  "Vulnerable",
  "Extinct",
];

const BG = "#0c1117";
const BG2 = "#131a22";
const BG3 = "#18222f";
const PANEL = "#1a2431";
const BORDER = "#2f3d4c";
const TEXT = "#f4f1eb";
const TEXT2 = "#c0b8aa";
const TEXT3 = "#8f98a5";
const GRID = "#2f3d4c";

const tooltipHandler = new vegaTooltip.Handler({ theme: "story" });
const embedOptions = {
  actions: false,
  renderer: "svg",
  tooltip: tooltipHandler.call,
};

const baseConfig = {
  background: "transparent",
  view: { stroke: "transparent" },
  axis: {
    domainColor: BORDER,
    domainWidth: 1,
    gridColor: GRID,
    gridOpacity: 0.18,
    tickColor: BORDER,
    labelColor: TEXT2,
    titleColor: TEXT2,
    labelFont: "Source Sans 3, sans-serif",
    titleFont: "Source Sans 3, sans-serif",
    labelFontSize: 11,
    titleFontSize: 12,
    titleFontWeight: 600,
    labelPadding: 6,
    titlePadding: 10,
    tickSize: 5,
    labelLimit: 240,
  },
  legend: {
    labelColor: TEXT2,
    titleColor: TEXT,
    labelFont: "Source Sans 3, sans-serif",
    titleFont: "Source Sans 3, sans-serif",
    labelFontSize: 11,
    titleFontSize: 11,
    titleFontWeight: 600,
    labelLimit: 220,
    symbolStrokeColor: BG,
    symbolStrokeWidth: 1,
  },
  title: {
    color: TEXT,
    font: "Playfair Display, serif",
    fontSize: 14,
    fontWeight: 700,
  },
};

// Data arrays
const STATUS_SUMMARY = [
  { "Threatened status": "Critically Endangered", count: 453, order: 1 },
  { "Threatened status": "Endangered", count: 860, order: 2 },
  { "Threatened status": "Vulnerable", count: 785, order: 3 },
  { "Threatened status": "Conservation Dependent", count: 7, order: 4 },
  { "Threatened status": "Extinct in the wild", count: 1, order: 5 },
  { "Threatened status": "Extinct", count: 102, order: 6 },
];

const KINGDOM_STATUS = [
  {
    Kingdom: "Animalia",
    "Threatened status": "Conservation Dependent",
    count: 7,
  },
  {
    Kingdom: "Animalia",
    "Threatened status": "Critically Endangered",
    count: 147,
  },
  { Kingdom: "Animalia", "Threatened status": "Endangered", count: 250 },
  { Kingdom: "Animalia", "Threatened status": "Extinct", count: 67 },
  {
    Kingdom: "Animalia",
    "Threatened status": "Extinct in the wild",
    count: 1,
  },
  { Kingdom: "Animalia", "Threatened status": "Vulnerable", count: 222 },
  {
    Kingdom: "Plantae",
    "Threatened status": "Critically Endangered",
    count: 306,
  },
  { Kingdom: "Plantae", "Threatened status": "Endangered", count: 610 },
  { Kingdom: "Plantae", "Threatened status": "Extinct", count: 35 },
  { Kingdom: "Plantae", "Threatened status": "Vulnerable", count: 563 },
];

const ANIMAL_CLASS = [
  {
    Class_name: "Birds",
    "Threatened status": "Critically Endangered",
    count: 18,
  },
  { Class_name: "Birds", "Threatened status": "Endangered", count: 69 },
  { Class_name: "Birds", "Threatened status": "Extinct", count: 22 },
  { Class_name: "Birds", "Threatened status": "Vulnerable", count: 77 },
  {
    Class_name: "Bony Fish",
    "Threatened status": "Critically Endangered",
    count: 26,
  },
  {
    Class_name: "Bony Fish",
    "Threatened status": "Endangered",
    count: 27,
  },
  { Class_name: "Bony Fish", "Threatened status": "Extinct", count: 1 },
  {
    Class_name: "Bony Fish",
    "Threatened status": "Vulnerable",
    count: 16,
  },
  {
    Class_name: "Crustaceans",
    "Threatened status": "Critically Endangered",
    count: 16,
  },
  {
    Class_name: "Crustaceans",
    "Threatened status": "Endangered",
    count: 26,
  },
  {
    Class_name: "Crustaceans",
    "Threatened status": "Vulnerable",
    count: 5,
  },
  {
    Class_name: "Frogs & Salamanders",
    "Threatened status": "Critically Endangered",
    count: 18,
  },
  {
    Class_name: "Frogs & Salamanders",
    "Threatened status": "Endangered",
    count: 15,
  },
  {
    Class_name: "Frogs & Salamanders",
    "Threatened status": "Extinct",
    count: 4,
  },
  {
    Class_name: "Frogs & Salamanders",
    "Threatened status": "Vulnerable",
    count: 16,
  },
  {
    Class_name: "Mammals",
    "Threatened status": "Critically Endangered",
    count: 22,
  },
  { Class_name: "Mammals", "Threatened status": "Endangered", count: 55 },
  { Class_name: "Mammals", "Threatened status": "Extinct", count: 34 },
  { Class_name: "Mammals", "Threatened status": "Vulnerable", count: 41 },
  {
    Class_name: "Reptiles",
    "Threatened status": "Critically Endangered",
    count: 14,
  },
  {
    Class_name: "Reptiles",
    "Threatened status": "Endangered",
    count: 44,
  },
  {
    Class_name: "Reptiles",
    "Threatened status": "Vulnerable",
    count: 44,
  },
];

const STATE_STATUS = [
  { state: "ACT", status: "Critically Endangered", count: 11 },
  { state: "ACT", status: "Endangered", count: 27 },
  { state: "ACT", status: "Vulnerable", count: 33 },
  { state: "NSW", status: "Critically Endangered", count: 152 },
  { state: "NSW", status: "Endangered", count: 285 },
  { state: "NSW", status: "Vulnerable", count: 284 },
  { state: "NSW", status: "Extinct", count: 33 },
  { state: "NT", status: "Critically Endangered", count: 14 },
  { state: "NT", status: "Endangered", count: 50 },
  { state: "NT", status: "Vulnerable", count: 78 },
  { state: "NT", status: "Extinct", count: 12 },
  { state: "QLD", status: "Critically Endangered", count: 86 },
  { state: "QLD", status: "Endangered", count: 199 },
  { state: "QLD", status: "Vulnerable", count: 290 },
  { state: "QLD", status: "Extinct", count: 33 },
  { state: "SA", status: "Critically Endangered", count: 31 },
  { state: "SA", status: "Endangered", count: 109 },
  { state: "SA", status: "Vulnerable", count: 146 },
  { state: "SA", status: "Extinct", count: 33 },
  { state: "TAS", status: "Critically Endangered", count: 29 },
  { state: "TAS", status: "Endangered", count: 80 },
  { state: "TAS", status: "Vulnerable", count: 108 },
  { state: "TAS", status: "Extinct", count: 13 },
  { state: "VIC", status: "Critically Endangered", count: 55 },
  { state: "VIC", status: "Endangered", count: 130 },
  { state: "VIC", status: "Vulnerable", count: 145 },
  { state: "VIC", status: "Extinct", count: 27 },
  { state: "WA", status: "Critically Endangered", count: 120 },
  { state: "WA", status: "Endangered", count: 192 },
  { state: "WA", status: "Vulnerable", count: 281 },
  { state: "WA", status: "Extinct", count: 21 },
];

const STATE_TOTALS = [
  { state: "ACT", count: 71, state_full: "Australian Capital Territory" },
  { state: "NSW", count: 760, state_full: "New South Wales" },
  { state: "NT", count: 155, state_full: "Northern Territory" },
  { state: "QLD", count: 612, state_full: "Queensland" },
  { state: "SA", count: 319, state_full: "South Australia" },
  { state: "TAS", count: 230, state_full: "Tasmania" },
  { state: "VIC", count: 357, state_full: "Victoria" },
  { state: "WA", count: 614, state_full: "Western Australia" },
];

const ENDEMIC_STATE = [
  {
    state: "ACT",
    state_full: "Australian Capital Territory",
    endemic_threatened: 0,
  },
  { state: "NSW", state_full: "New South Wales", endemic_threatened: 66 },
  {
    state: "NT",
    state_full: "Northern Territory",
    endemic_threatened: 24,
  },
  { state: "QLD", state_full: "Queensland", endemic_threatened: 91 },
  { state: "SA", state_full: "South Australia", endemic_threatened: 31 },
  { state: "TAS", state_full: "Tasmania", endemic_threatened: 48 },
  { state: "VIC", state_full: "Victoria", endemic_threatened: 23 },
  {
    state: "WA",
    state_full: "Western Australia",
    endemic_threatened: 69,
  },
];

const HOTSPOT = [
  { state: "ACT", total: 71, endemic: 0, pct_endemic: 0 },
  { state: "NSW", total: 760, endemic: 66, pct_endemic: 8.7 },
  { state: "NT", total: 155, endemic: 24, pct_endemic: 15.5 },
  { state: "QLD", total: 612, endemic: 91, pct_endemic: 14.9 },
  { state: "SA", total: 319, endemic: 31, pct_endemic: 9.7 },
  { state: "TAS", total: 230, endemic: 48, pct_endemic: 20.9 },
  { state: "VIC", total: 357, endemic: 23, pct_endemic: 6.4 },
  { state: "WA", total: 614, endemic: 69, pct_endemic: 11.2 },
];

const CO_OCCUR = [
  { state1: "NSW", state2: "QLD", shared: 224 },
  { state1: "NSW", state2: "VIC", shared: 202 },
  { state1: "SA", state2: "VIC", shared: 170 },
  { state1: "NSW", state2: "SA", shared: 140 },
  { state1: "QLD", state2: "VIC", shared: 94 },
  { state1: "QLD", state2: "SA", shared: 89 },
  { state1: "SA", state2: "WA", shared: 88 },
  { state1: "NT", state2: "WA", shared: 84 },
  { state1: "TAS", state2: "VIC", shared: 83 },
  { state1: "QLD", state2: "WA", shared: 81 },
  { state1: "NSW", state2: "WA", shared: 77 },
  { state1: "NSW", state2: "NT", shared: 64 },
  { state1: "NSW", state2: "TAS", shared: 61 },
  { state1: "VIC", state2: "WA", shared: 57 },
  { state1: "NT", state2: "QLD", shared: 55 },
  { state1: "QLD", state2: "TAS", shared: 42 },
  { state1: "SA", state2: "TAS", shared: 38 },
  { state1: "NT", state2: "SA", shared: 35 },
  { state1: "NT", state2: "VIC", shared: 26 },
  { state1: "NT", state2: "TAS", shared: 19 },
  { state1: "WA", state2: "VIC", shared: 57 },
  { state1: "WA", state2: "TAS", shared: 25 },
  { state1: "ACT", state2: "NSW", shared: 58 },
  { state1: "ACT", state2: "VIC", shared: 41 },
  { state1: "ACT", state2: "QLD", shared: 23 },
  { state1: "ACT", state2: "SA", shared: 17 },
  { state1: "ACT", state2: "TAS", shared: 12 },
  { state1: "ACT", state2: "WA", shared: 9 },
];

const BIRD_TREND = [
  {
    year: 1990,
    group: "Critically Endangered",
    mean_count: 195.89,
    index: 100,
  },
  {
    year: 1991,
    group: "Critically Endangered",
    mean_count: 139.54,
    index: 71.2,
  },
  {
    year: 1992,
    group: "Critically Endangered",
    mean_count: 239.97,
    index: 122.5,
  },
  {
    year: 1993,
    group: "Critically Endangered",
    mean_count: 87.24,
    index: 44.5,
  },
  {
    year: 1994,
    group: "Critically Endangered",
    mean_count: 106.67,
    index: 54.5,
  },
  {
    year: 1995,
    group: "Critically Endangered",
    mean_count: 98.31,
    index: 50.2,
  },
  {
    year: 1996,
    group: "Critically Endangered",
    mean_count: 81.35,
    index: 41.5,
  },
  {
    year: 1997,
    group: "Critically Endangered",
    mean_count: 57.83,
    index: 29.5,
  },
  {
    year: 1998,
    group: "Critically Endangered",
    mean_count: 78.57,
    index: 40.1,
  },
  {
    year: 1999,
    group: "Critically Endangered",
    mean_count: 53.38,
    index: 27.2,
  },
  {
    year: 2000,
    group: "Critically Endangered",
    mean_count: 112.14,
    index: 57.2,
  },
  {
    year: 2001,
    group: "Critically Endangered",
    mean_count: 59.42,
    index: 30.3,
  },
  {
    year: 2002,
    group: "Critically Endangered",
    mean_count: 68.16,
    index: 34.8,
  },
  {
    year: 2003,
    group: "Critically Endangered",
    mean_count: 111.3,
    index: 56.8,
  },
  {
    year: 2004,
    group: "Critically Endangered",
    mean_count: 83.46,
    index: 42.6,
  },
  {
    year: 2005,
    group: "Critically Endangered",
    mean_count: 163.35,
    index: 83.4,
  },
  {
    year: 2006,
    group: "Critically Endangered",
    mean_count: 50.14,
    index: 25.6,
  },
  {
    year: 2007,
    group: "Critically Endangered",
    mean_count: 145.91,
    index: 74.5,
  },
  {
    year: 2008,
    group: "Critically Endangered",
    mean_count: 31.88,
    index: 16.3,
  },
  {
    year: 2009,
    group: "Critically Endangered",
    mean_count: 24.13,
    index: 12.3,
  },
  {
    year: 2010,
    group: "Critically Endangered",
    mean_count: 37.5,
    index: 19.1,
  },
  {
    year: 2011,
    group: "Critically Endangered",
    mean_count: 48.2,
    index: 24.6,
  },
  {
    year: 2012,
    group: "Critically Endangered",
    mean_count: 31.1,
    index: 15.9,
  },
  {
    year: 2013,
    group: "Critically Endangered",
    mean_count: 22.5,
    index: 11.5,
  },
  {
    year: 2014,
    group: "Critically Endangered",
    mean_count: 19.8,
    index: 10.1,
  },
  {
    year: 2015,
    group: "Critically Endangered",
    mean_count: 28.6,
    index: 14.6,
  },
  {
    year: 2016,
    group: "Critically Endangered",
    mean_count: 24.1,
    index: 12.3,
  },
  {
    year: 2017,
    group: "Critically Endangered",
    mean_count: 35.2,
    index: 18.0,
  },
  {
    year: 2018,
    group: "Critically Endangered",
    mean_count: 28.7,
    index: 14.6,
  },
  {
    year: 2019,
    group: "Critically Endangered",
    mean_count: 18.4,
    index: 9.4,
  },
  {
    year: 2020,
    group: "Critically Endangered",
    mean_count: 21.3,
    index: 10.9,
  },
  {
    year: 2021,
    group: "Critically Endangered",
    mean_count: 17.9,
    index: 9.1,
  },
  {
    year: 2022,
    group: "Critically Endangered",
    mean_count: 15.2,
    index: 7.8,
  },
  { year: 1990, group: "Endangered", mean_count: 175.0, index: 100 },
  { year: 1995, group: "Endangered", mean_count: 142.0, index: 81.1 },
  { year: 2000, group: "Endangered", mean_count: 130.0, index: 74.3 },
  { year: 2005, group: "Endangered", mean_count: 118.0, index: 67.4 },
  { year: 2010, group: "Endangered", mean_count: 95.0, index: 54.3 },
  { year: 2015, group: "Endangered", mean_count: 88.0, index: 50.3 },
  { year: 2019, group: "Endangered", mean_count: 72.0, index: 41.1 },
  { year: 2022, group: "Endangered", mean_count: 65.0, index: 37.1 },
  { year: 1990, group: "Vulnerable", mean_count: 210.0, index: 100 },
  { year: 1995, group: "Vulnerable", mean_count: 195.0, index: 92.9 },
  { year: 2000, group: "Vulnerable", mean_count: 180.0, index: 85.7 },
  { year: 2005, group: "Vulnerable", mean_count: 160.0, index: 76.2 },
  { year: 2010, group: "Vulnerable", mean_count: 145.0, index: 69.0 },
  { year: 2015, group: "Vulnerable", mean_count: 130.0, index: 61.9 },
  { year: 2019, group: "Vulnerable", mean_count: 118.0, index: 56.2 },
  { year: 2022, group: "Vulnerable", mean_count: 110.0, index: 52.4 },
];

const BIRDS_STATE = [
  {
    State: "Australian Capital Territory",
    EPBCStatus: "Endangered",
    count: 2,
  },
  {
    State: "Australian Capital Territory",
    EPBCStatus: "Vulnerable",
    count: 6,
  },
  {
    State: "New South Wales",
    EPBCStatus: "Critically Endangered",
    count: 3,
  },
  { State: "New South Wales", EPBCStatus: "Endangered", count: 15 },
  { State: "New South Wales", EPBCStatus: "Vulnerable", count: 13 },
  {
    State: "Northern Territory",
    EPBCStatus: "Critically Endangered",
    count: 2,
  },
  { State: "Northern Territory", EPBCStatus: "Endangered", count: 7 },
  { State: "Northern Territory", EPBCStatus: "Vulnerable", count: 7 },
  { State: "Queensland", EPBCStatus: "Critically Endangered", count: 3 },
  { State: "Queensland", EPBCStatus: "Endangered", count: 10 },
  { State: "Queensland", EPBCStatus: "Vulnerable", count: 9 },
  {
    State: "South Australia",
    EPBCStatus: "Critically Endangered",
    count: 3,
  },
  { State: "South Australia", EPBCStatus: "Endangered", count: 11 },
  { State: "South Australia", EPBCStatus: "Vulnerable", count: 11 },
  { State: "Tasmania", EPBCStatus: "Critically Endangered", count: 2 },
  { State: "Tasmania", EPBCStatus: "Endangered", count: 7 },
  { State: "Tasmania", EPBCStatus: "Vulnerable", count: 8 },
  { State: "Victoria", EPBCStatus: "Critically Endangered", count: 5 },
  { State: "Victoria", EPBCStatus: "Endangered", count: 11 },
  { State: "Victoria", EPBCStatus: "Vulnerable", count: 13 },
  {
    State: "Western Australia",
    EPBCStatus: "Critically Endangered",
    count: 3,
  },
  { State: "Western Australia", EPBCStatus: "Endangered", count: 8 },
  { State: "Western Australia", EPBCStatus: "Vulnerable", count: 10 },
];

const TOP_BIRDS = [
  {
    CommonName: "South-eastern Brown Treecreeper",
    sites: 161,
    status: "Vulnerable",
  },
  { CommonName: "Gang-gang Cockatoo", sites: 74, status: "Endangered" },
  {
    CommonName: "South-east Southern Whiteface",
    sites: 118,
    status: "Vulnerable",
  },
  { CommonName: "Red-necked Stint", sites: 90, status: "Endangered" },
  {
    CommonName: "South-eastern Hooded Robin",
    sites: 87,
    status: "Endangered",
  },
  { CommonName: "Common Greenshank", sites: 84, status: "Endangered" },
  {
    CommonName: "Sharp-tailed Sandpiper",
    sites: 77,
    status: "Vulnerable",
  },
  { CommonName: "Diamond Firetail", sites: 72, status: "Vulnerable" },
  {
    CommonName: "Curlew Sandpiper",
    sites: 70,
    status: "Critically Endangered",
  },
  {
    CommonName: "Far Eastern Curlew",
    sites: 59,
    status: "Critically Endangered",
  },
  { CommonName: "Lesser Sand Plover", sites: 55, status: "Endangered" },
  { CommonName: "Painted Honeyeater", sites: 53, status: "Vulnerable" },
  { CommonName: "Red Knot", sites: 53, status: "Vulnerable" },
  { CommonName: "Black-tailed Godwit", sites: 53, status: "Endangered" },
  { CommonName: "Little Curlew", sites: 38, status: "Vulnerable" },
];

const TOP_FAM = [
  { family: "Orchidaceae", status: "Critically Endangered", count: 66 },
  { family: "Orchidaceae", status: "Endangered", count: 108 },
  { family: "Orchidaceae", status: "Vulnerable", count: 64 },
  { family: "Myrtaceae", status: "Critically Endangered", count: 37 },
  { family: "Myrtaceae", status: "Endangered", count: 68 },
  { family: "Myrtaceae", status: "Vulnerable", count: 91 },
  { family: "Fabaceae", status: "Critically Endangered", count: 25 },
  { family: "Fabaceae", status: "Endangered", count: 67 },
  { family: "Fabaceae", status: "Vulnerable", count: 62 },
  { family: "Proteaceae", status: "Critically Endangered", count: 30 },
  { family: "Proteaceae", status: "Endangered", count: 63 },
  { family: "Proteaceae", status: "Vulnerable", count: 44 },
  { family: "Rutaceae", status: "Critically Endangered", count: 21 },
  { family: "Rutaceae", status: "Endangered", count: 31 },
  { family: "Rutaceae", status: "Vulnerable", count: 36 },
  { family: "Asteraceae", status: "Critically Endangered", count: 3 },
  { family: "Asteraceae", status: "Endangered", count: 16 },
  { family: "Asteraceae", status: "Vulnerable", count: 31 },
  { family: "Parastacidae", status: "Critically Endangered", count: 16 },
  { family: "Parastacidae", status: "Endangered", count: 26 },
  { family: "Parastacidae", status: "Vulnerable", count: 5 },
  { family: "Lamiaceae", status: "Critically Endangered", count: 11 },
  { family: "Lamiaceae", status: "Endangered", count: 14 },
  { family: "Lamiaceae", status: "Vulnerable", count: 17 },
  { family: "Scincidae", status: "Critically Endangered", count: 8 },
  { family: "Scincidae", status: "Endangered", count: 19 },
  { family: "Scincidae", status: "Vulnerable", count: 12 },
  { family: "Muridae", status: "Critically Endangered", count: 1 },
  { family: "Muridae", status: "Endangered", count: 7 },
  { family: "Muridae", status: "Vulnerable", count: 11 },
];

const POP_TREND = [
  { year: 1990, group: "Birds", mean_count: 160.2 },
  { year: 1995, group: "Birds", mean_count: 145.0 },
  { year: 2000, group: "Birds", mean_count: 132.0 },
  { year: 2005, group: "Birds", mean_count: 118.0 },
  { year: 2010, group: "Birds", mean_count: 98.0 },
  { year: 2015, group: "Birds", mean_count: 85.0 },
  { year: 2018, group: "Birds", mean_count: 74.0 },
  { year: 2020, group: "Birds", mean_count: 65.0 },
  { year: 2022, group: "Birds", mean_count: 58.0 },
  { year: 1990, group: "Mammals", mean_count: 95.0 },
  { year: 1995, group: "Mammals", mean_count: 88.0 },
  { year: 2000, group: "Mammals", mean_count: 79.0 },
  { year: 2005, group: "Mammals", mean_count: 68.0 },
  { year: 2010, group: "Mammals", mean_count: 52.0 },
  { year: 2015, group: "Mammals", mean_count: 41.0 },
  { year: 2018, group: "Mammals", mean_count: 33.0 },
  { year: 2020, group: "Mammals", mean_count: 27.0 },
  { year: 2022, group: "Mammals", mean_count: 22.0 },
  { year: 1990, group: "Amphibians", mean_count: 120.0 },
  { year: 1995, group: "Amphibians", mean_count: 95.0 },
  { year: 2000, group: "Amphibians", mean_count: 70.0 },
  { year: 2005, group: "Amphibians", mean_count: 55.0 },
  { year: 2010, group: "Amphibians", mean_count: 42.0 },
  { year: 2015, group: "Amphibians", mean_count: 35.0 },
  { year: 2018, group: "Amphibians", mean_count: 28.0 },
  { year: 2020, group: "Amphibians", mean_count: 23.0 },
  { year: 2022, group: "Amphibians", mean_count: 18.0 },
];

const MONITORING_LOCATIONS_RAW = [
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -25.0153,
    lon: 114.4114,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -18.3111,
    lon: 122.3163,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -20.6605,
    lon: 117.0796,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -15.7141,
    lon: 120.8315,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -31.9153,
    lon: 115.4916,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -37.847,
    lon: 143.2518,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -33.7985,
    lon: 134.7935,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -40.4357,
    lon: 147.8211,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -22.4051,
    lon: 114.4196,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -33.6868,
    lon: 151.3158,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -32.7642,
    lon: 134.4945,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -40.448,
    lon: 144.5314,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -19.5994,
    lon: 147.3552,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -38.321,
    lon: 144.2402,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -42.656,
    lon: 147.752,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -12.7242,
    lon: 131.1775,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -34.9575,
    lon: 137.4744,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -33.2071,
    lon: 151.5581,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -33.9139,
    lon: 137.9382,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -35.7747,
    lon: 139.2178,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -11.9893,
    lon: 134.579,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -29.2459,
    lon: 153.2594,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -12.674,
    lon: 136.4093,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -37.3493,
    lon: 140.0268,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -37.7506,
    lon: 148.9293,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -28.3574,
    lon: 114.4414,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -31.2316,
    lon: 152.798,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -32.5201,
    lon: 151.189,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -32.066,
    lon: 127.5511,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.6618,
    lon: 150.8783,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -22.6756,
    lon: 134.1468,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -34.6955,
    lon: 116.1574,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -35.2652,
    lon: 150.66,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -29.7288,
    lon: 126.694,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -14.3065,
    lon: 141.8775,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -32.763,
    lon: 136.9455,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -38.5121,
    lon: 142.5393,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -18.763,
    lon: 146.4544,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.2247,
    lon: 151.0052,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -26.8755,
    lon: 114.3104,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -25.7517,
    lon: 113.0045,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -16.6887,
    lon: 140.4145,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -21.092,
    lon: 149.3839,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -17.2769,
    lon: 146.0729,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -27.2052,
    lon: 153.3375,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -25.1012,
    lon: 152.8141,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -24.2295,
    lon: 151.7723,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -22.673,
    lon: 150.5462,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -14.7268,
    lon: 145.1059,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -18.1753,
    lon: 146.2083,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -22.5986,
    lon: 150.9014,
  },
  {
    common_name: "Lesser Sand Plover",
    species: "Charadrius_mongolus",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -28.1695,
    lon: 153.6797,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -25.0153,
    lon: 114.4114,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -18.3111,
    lon: 122.3163,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -31.9153,
    lon: 115.4916,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -15.7141,
    lon: 120.8315,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -33.7985,
    lon: 134.7935,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -33.9139,
    lon: 137.9382,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -33.895,
    lon: 122.5969,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -22.4051,
    lon: 114.4196,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -32.7642,
    lon: 134.4945,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Tasmania",
    lat: -40.448,
    lon: 144.5314,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -34.9575,
    lon: 137.4744,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -20.6605,
    lon: 117.0796,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -29.2459,
    lon: 153.2594,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -12.7242,
    lon: 131.1775,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Tasmania",
    lat: -40.4357,
    lon: 147.8211,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -12.674,
    lon: 136.4093,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -28.3574,
    lon: 114.4414,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -34.6955,
    lon: 116.1574,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -29.9069,
    lon: 115.383,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -22.6756,
    lon: 134.1468,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.321,
    lon: 144.2402,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -29.7288,
    lon: 126.694,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.6618,
    lon: 150.8783,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -18.763,
    lon: 146.4544,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -26.8755,
    lon: 114.3104,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -35.9292,
    lon: 137.2438,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -16.6887,
    lon: 140.4145,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -21.092,
    lon: 149.3839,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -19.5994,
    lon: 147.3552,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -17.2769,
    lon: 146.0729,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -27.2052,
    lon: 153.3375,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -25.1012,
    lon: 152.8141,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -22.673,
    lon: 150.5462,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -24.2295,
    lon: 151.7723,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -18.1753,
    lon: 146.2083,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -14.7268,
    lon: 145.1059,
  },
  {
    common_name: "Greater Sand Plover",
    species: "Charadrius_leschenaultii",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -22.5986,
    lon: 150.9014,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -25.0153,
    lon: 114.4114,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -18.3111,
    lon: 122.3163,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -31.9153,
    lon: 115.4916,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -23.6767,
    lon: 132.5498,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -32.5201,
    lon: 151.189,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -32.7642,
    lon: 134.4945,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -33.9139,
    lon: 137.9382,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -35.1862,
    lon: 142.3331,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -40.4357,
    lon: 147.8211,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.6618,
    lon: 150.8783,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -33.2071,
    lon: 151.5581,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -35.7747,
    lon: 139.2178,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -20.6605,
    lon: 117.0796,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -11.9893,
    lon: 134.579,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -29.2459,
    lon: 153.2594,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Northern Territory",
    lat: -12.7242,
    lon: 131.1775,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.7952,
    lon: 145.1549,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -28.3574,
    lon: 114.4414,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -31.2316,
    lon: 152.798,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -34.6955,
    lon: 116.1574,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -38.321,
    lon: 144.2402,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -37.847,
    lon: 143.2518,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Victoria",
    lat: -36.3188,
    lon: 144.9278,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -20.5816,
    lon: 139.7437,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -33.895,
    lon: 122.5969,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -37.3493,
    lon: 140.0268,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -33.7985,
    lon: 134.7935,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -35.2652,
    lon: 150.66,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -42.656,
    lon: 147.752,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Western Australia",
    lat: -29.7288,
    lon: 126.694,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -14.3065,
    lon: 141.8775,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -31.7303,
    lon: 136.5455,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -20.5766,
    lon: 146.001,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Tasmania",
    lat: -40.448,
    lon: 144.5314,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -18.763,
    lon: 146.4544,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -35.5804,
    lon: 144.9212,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.2247,
    lon: 151.0052,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -28.4196,
    lon: 153.6112,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "South Australia",
    lat: -35.9292,
    lon: 137.2438,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -16.6887,
    lon: 140.4145,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -27.2052,
    lon: 153.3375,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -21.092,
    lon: 149.3839,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -17.2769,
    lon: 146.0729,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -19.5994,
    lon: 147.3552,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -25.1012,
    lon: 152.8141,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -22.673,
    lon: 150.5462,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -24.2295,
    lon: 151.7723,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -27.7708,
    lon: 150.908,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "Queensland",
    lat: -22.5986,
    lon: 150.9014,
  },
  {
    common_name: "Black-tailed Godwit",
    species: "Limosa_limosa",
    group: "Birds",
    status: "Endangered",
    state: "New South Wales",
    lat: -28.1695,
    lon: 153.6797,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -25.0153,
    lon: 114.4114,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -18.3111,
    lon: 122.3163,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -31.9153,
    lon: 115.4916,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -32.5201,
    lon: 151.189,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -34.6955,
    lon: 116.1574,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -37.847,
    lon: 143.2518,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -33.7985,
    lon: 134.7935,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -33.9139,
    lon: 137.9382,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.321,
    lon: 144.2402,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -22.4051,
    lon: 114.4196,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.6868,
    lon: 151.3158,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -32.7642,
    lon: 134.4945,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Tasmania",
    lat: -40.448,
    lon: 144.5314,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -35.955,
    lon: 150.2451,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Tasmania",
    lat: -40.4357,
    lon: 147.8211,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -34.9575,
    lon: 137.4744,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -35.2652,
    lon: 150.66,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.6618,
    lon: 150.8783,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.2071,
    lon: 151.5581,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -35.7747,
    lon: 139.2178,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -20.6605,
    lon: 117.0796,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -11.9893,
    lon: 134.579,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -29.2459,
    lon: 153.2594,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -12.7242,
    lon: 131.1775,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -33.895,
    lon: 122.5969,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -31.2316,
    lon: 152.798,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -28.3574,
    lon: 114.4414,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.5121,
    lon: 142.5393,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -32.4133,
    lon: 117.1793,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -36.5332,
    lon: 149.739,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Tasmania",
    lat: -42.656,
    lon: 147.752,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -37.7506,
    lon: 148.9293,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -37.3493,
    lon: 140.0268,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -35.9292,
    lon: 137.2438,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -29.7288,
    lon: 126.694,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.3855,
    lon: 141.3016,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.2247,
    lon: 151.0052,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "South Australia",
    lat: -32.763,
    lon: 136.9455,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -18.763,
    lon: 146.4544,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -26.8755,
    lon: 114.3104,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -27.2052,
    lon: 153.3375,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -16.6887,
    lon: 140.4145,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -21.092,
    lon: 149.3839,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -17.2769,
    lon: 146.0729,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -19.5994,
    lon: 147.3552,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -25.1012,
    lon: 152.8141,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -22.673,
    lon: 150.5462,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Queensland",
    lat: -24.2295,
    lon: 151.7723,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "Northern Territory",
    lat: -22.6756,
    lon: 134.1468,
  },
  {
    common_name: "Red Knot",
    species: "Calidris_canutus",
    group: "Birds",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -28.1695,
    lon: 153.6797,
  },
  {
    common_name: "Gould's Petrel",
    species: "Pterodroma_leucoptera",
    group: "Birds",
    status: null,
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Gould's Petrel",
    species: "Pterodroma_leucoptera",
    group: "Birds",
    status: null,
    state: "New South Wales",
    lat: -35.955,
    lon: 150.2451,
  },
  {
    common_name: "White-bellied Frog",
    species: "Anstisia_alba",
    group: "Amphibians",
    status: "Critically Endangered",
    state: "Western Australia",
    lat: -34.6955,
    lon: 116.1574,
  },
  {
    common_name: "White-bellied Frog",
    species: "Anstisia_alba",
    group: "Amphibians",
    status: "Critically Endangered",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Orange-bellied Frog",
    species: "Anstisia_vitellina",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Western Australia",
    lat: -34.1505,
    lon: 116.6498,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.8501,
    lon: 149.0708,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.8851,
    lon: 150.8078,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.2247,
    lon: 151.0052,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.6618,
    lon: 150.8783,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -29.8207,
    lon: 153.4154,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -32.5201,
    lon: 151.189,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.6868,
    lon: 151.3158,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -35.2652,
    lon: 150.66,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -31.2316,
    lon: 152.798,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -32.366,
    lon: 152.2973,
  },
  {
    common_name: "Green and Golden Bell Frog",
    species: "Litoria_aurea",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -36.1397,
    lon: 149.1057,
  },
  {
    common_name: "Booroolong Frog",
    species: "Litoria_booroolongensis",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.1382,
    lon: 148.3764,
  },
  {
    common_name: "Booroolong Frog",
    species: "Litoria_booroolongensis",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -35.5939,
    lon: 148.3174,
  },
  {
    common_name: "Booroolong Frog",
    species: "Litoria_booroolongensis",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.8501,
    lon: 149.0708,
  },
  {
    common_name: "Tasmanian Tree Frog",
    species: "Litoria_burrowsae",
    group: "Amphibians",
    status: null,
    state: "Tasmania",
    lat: -42.5662,
    lon: 145.6212,
  },
  {
    common_name: "Tasmanian Tree Frog",
    species: "Litoria_burrowsae",
    group: "Amphibians",
    status: null,
    state: "Tasmania",
    lat: -43.133,
    lon: 146.7429,
  },
  {
    common_name: "Australian Lace-lid",
    species: "Litoria_dayi",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Queensland",
    lat: -18.8326,
    lon: 146.0068,
  },
  {
    common_name: "Kroombit Tree Frog",
    species: "Litoria_kroombitensis",
    group: "Amphibians",
    status: "Critically Endangered",
    state: "Queensland",
    lat: -24.2295,
    lon: 151.7723,
  },
  {
    common_name: "Northern Heath Frog",
    species: "Litoria_littlejohni",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -34.2247,
    lon: 151.0052,
  },
  {
    common_name: "Northern Heath Frog",
    species: "Litoria_littlejohni",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -33.2071,
    lon: 151.5581,
  },
  {
    common_name: "Southern Owl Frog",
    species: "Heleioporus_australiacus_flavopunctatus",
    group: "Amphibians",
    status: "Endangered",
    state: "New South Wales",
    lat: -36.5332,
    lon: 149.739,
  },
  {
    common_name: "Alpine Tree Frog",
    species: "Litoria_verreauxii_alpina",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -37.209,
    lon: 146.8453,
  },
  {
    common_name: "Armoured Mist Frog",
    species: "Litoria_lorica",
    group: "Amphibians",
    status: "Critically Endangered",
    state: "Queensland",
    lat: -16.0942,
    lon: 145.3602,
  },
  {
    common_name: "Kuranda Tree Frog",
    species: "Litoria_myola",
    group: "Amphibians",
    status: "Critically Endangered",
    state: "Queensland",
    lat: -16.5884,
    lon: 145.7091,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Queensland",
    lat: -27.1534,
    lon: 152.8243,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Queensland",
    lat: -27.2052,
    lon: 153.3375,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -28.4196,
    lon: 153.6112,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -28.5964,
    lon: 153.1884,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -29.2459,
    lon: 153.2594,
  },
  {
    common_name: "Wallum Sedge Frog",
    species: "Litoria_olongburensis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -29.8207,
    lon: 153.4154,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.8501,
    lon: 149.0708,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -37.847,
    lon: 143.2518,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -37.2197,
    lon: 144.8841,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.3864,
    lon: 146.2604,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.7952,
    lon: 145.1549,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.7093,
    lon: 144.581,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -34.1355,
    lon: 147.2989,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "New South Wales",
    lat: -33.5561,
    lon: 142.5487,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -36.8579,
    lon: 143.9087,
  },
  {
    common_name: "Southern Bell Frog",
    species: "Litoria_raniformis",
    group: "Amphibians",
    status: "Vulnerable",
    state: "Victoria",
    lat: -38.321,
    lon: 144.2402,
  },
  {
    common_name: "Common Mist Frog",
    species: "Litoria_rheocola",
    group: "Amphibians",
    status: null,
    state: "Queensland",
    lat: -16.0942,
    lon: 145.3602,
  },
  {
    common_name: "Common Mist Frog",
    species: "Litoria_rheocola",
    group: "Amphibians",
    status: null,
    state: "Queensland",
    lat: -18.1263,
    lon: 145.7201,
  },
  {
    common_name: "Common Mist Frog",
    species: "Litoria_rheocola",
    group: "Amphibians",
    status: null,
    state: "Queensland",
    lat: -17.4353,
    lon: 145.76,
  },
];

const AUS_TOPOJSON_URL =
  "https://raw.githubusercontent.com/FIT3179/Vega-Lite/main/3_choropleth_map/js/ne_110m_admin_0_countries.topojson";
const AUS_STATES_URL =
  "https://raw.githubusercontent.com/rowanhogan/australian-states/master/states.min.geojson";

const MONITORING_LOCATIONS = MONITORING_LOCATIONS_RAW.filter(
  (d) => d.status !== null,
);

const W = (id) => document.getElementById(id).clientWidth - 20 || 700;

// Charts
const chart1 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 320,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: STATUS_SUMMARY },
  transform: [
    {
      filter:
        "datum['Threatened status'] !== 'Extinct in the wild' && datum['Threatened status'] !== 'Conservation Dependent'",
    },
  ],
  encoding: {
    theta: { field: "count", type: "quantitative", stack: true },
    color: {
      field: "Threatened status",
      type: "nominal",
      scale: {
        domain: [
          "Critically Endangered",
          "Endangered",
          "Vulnerable",
          "Extinct",
        ],
        range: STATUS_RANGE,
      },
      legend: {
        orient: "bottom",
        anchor: "middle",
        direction: "horizontal",
        columns: 4,
        title: null,
      },
    },
    tooltip: [
      { field: "Threatened status", title: "Status" },
      { field: "count", title: "Species", format: "," },
    ],
  },
  mark: {
    type: "arc",
    outerRadius: 128,
    innerRadius: 62,
    stroke: BG,
    strokeWidth: 2,
  },
};

vegaEmbed("#chart1", chart1, embedOptions);

const chart2 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 260,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: {
    values: KINGDOM_STATUS.filter((d) =>
      ["Critically Endangered", "Endangered", "Vulnerable", "Extinct"].includes(
        d["Threatened status"],
      ),
    ),
  },
  mark: { type: "bar", cornerRadiusTopLeft: 2, cornerRadiusTopRight: 2 },
  encoding: {
    x: {
      field: "Kingdom",
      type: "nominal",
      axis: { labelAngle: 0 },
      title: null,
    },
    xOffset: {
      field: "Threatened status",
      type: "nominal",
      sort: ["Critically Endangered", "Endangered", "Vulnerable", "Extinct"],
    },
    y: {
      field: "count",
      type: "quantitative",
      title: "Species Count",
      axis: { grid: true, gridColor: GRID },
    },
    color: {
      field: "Threatened status",
      type: "nominal",
      scale: {
        domain: [
          "Critically Endangered",
          "Endangered",
          "Vulnerable",
          "Extinct",
        ],
        range: STATUS_RANGE,
      },
      legend: {
        orient: "bottom",
        anchor: "middle",
        direction: "horizontal",
        columns: 4,
        title: null,
      },
    },
    tooltip: [
      { field: "Kingdom", title: "Kingdom" },
      { field: "Threatened status", title: "Status" },
      { field: "count", title: "Species", format: "," },
    ],
  },
};
vegaEmbed("#chart2", chart2, embedOptions);

const chart3 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 280,
  config: baseConfig,
  data: { values: ANIMAL_CLASS },
  mark: { type: "bar", cornerRadius: 2 },
  encoding: {
    y: {
      field: "Class_name",
      type: "nominal",
      title: null,
      sort: { field: "count", op: "sum", order: "descending" },
      axis: { labelFontSize: 12 },
    },
    x: {
      field: "count",
      type: "quantitative",
      title: "Number of Threatened Species",
      axis: { grid: true, gridColor: GRID },
    },
    color: {
      field: "Threatened status",
      type: "nominal",
      scale: {
        domain: [
          "Critically Endangered",
          "Endangered",
          "Vulnerable",
          "Extinct",
        ],
        range: STATUS_RANGE,
      },
      legend: { orient: "top", title: null, direction: "horizontal" },
    },
    order: {
      field: "Threatened status",
      sort: ["Critically Endangered", "Endangered", "Vulnerable", "Extinct"],
    },
    tooltip: [
      { field: "Class_name", title: "Class" },
      { field: "Threatened status", title: "Status" },
      { field: "count", title: "Species" },
    ],
  },
};
vegaEmbed("#chart3", chart3, embedOptions);

const map1 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 420,
  config: baseConfig,
  projection: { type: "mercator", center: [133, -28], scale: 650 },
  data: {
    url: "https://raw.githubusercontent.com/SohamDarekar/fit3179-assignment2/refs/heads/main/australia-states.json",
    format: { type: "topojson", feature: "STE_2021_AUST_GDA2020" },
  },
  transform: [
    {
      lookup: "properties.STE_NAME21",
      from: {
        data: { values: STATE_TOTALS },
        key: "state_full",
        fields: ["count", "state"],
      },
    },
  ],
  mark: { type: "geoshape", stroke: BG, strokeWidth: 1.5 },
  encoding: {
    color: {
      field: "count",
      type: "quantitative",
      title: "Threatened Species",
      scale: {
        range: ["#22303e", "#344556", "#516678", STATUS_COLORS["Critically Endangered"]],
        domainMin: 0,
      },
      legend: { orient: "bottom-right", titleFontSize: 11 },
    },
    tooltip: [
      { field: "properties.STE_NAME21", title: "State" },
      { field: "count", title: "Threatened Species", format: "," },
    ],
  },
};
vegaEmbed("#map1", map1, embedOptions);

const chart4 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 340,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: STATE_STATUS },
  mark: { type: "bar", cornerRadius: 2 },
  encoding: {
    x: {
      field: "count",
      type: "quantitative",
      title: "Species Count",
      axis: { grid: true, gridColor: GRID },
    },
    y: {
      field: "state",
      type: "nominal",
      title: null,
      sort: { field: "count", op: "sum", order: "descending" },
    },
    color: {
      field: "status",
      type: "nominal",
      scale: {
        domain: [
          "Critically Endangered",
          "Endangered",
          "Vulnerable",
          "Extinct",
        ],
        range: STATUS_RANGE,
      },
      legend: {
        orient: "bottom",
        anchor: "middle",
        direction: "horizontal",
        columns: 4,
        title: null,
      },
    },
    order: {
      field: "status",
      sort: ["Critically Endangered", "Endangered", "Vulnerable", "Extinct"],
    },
    tooltip: [
      { field: "state", title: "State" },
      { field: "status", title: "Status" },
      { field: "count", title: "Species", format: "," },
    ],
  },
};
vegaEmbed("#chart4", chart4, embedOptions);

const chart5 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 340,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
  },
  data: { values: ENDEMIC_STATE.filter((d) => d.endemic_threatened > 0) },
  layer: [
    {
      mark: { type: "rule", color: GRID, strokeWidth: 1 },
      encoding: {
        y: {
          field: "state",
          type: "nominal",
          sort: { field: "endemic_threatened", order: "descending" },
        },
        x: { value: 0 },
        x2: { field: "endemic_threatened", type: "quantitative" },
      },
    },
    {
      mark: { type: "point", filled: true, size: 140 },
      encoding: {
        y: {
          field: "state",
          type: "nominal",
          title: null,
          sort: { field: "endemic_threatened", order: "descending" },
        },
        x: {
          field: "endemic_threatened",
          type: "quantitative",
          title: "Single-State Endemic Threatened Species",
          axis: { grid: true, gridColor: GRID },
        },
        color: { value: STATUS_COLORS.Endangered },
        tooltip: [
          { field: "state_full", title: "State" },
          { field: "endemic_threatened", title: "Single-State Endemics" },
        ],
      },
    },
  ],
};
vegaEmbed("#chart5", chart5, embedOptions);

const map2 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 440,
  config: baseConfig,
  projection: { type: "mercator", center: [133, -28], scale: 650 },
  layer: [
    {
      data: {
        url: "https://raw.githubusercontent.com/SohamDarekar/fit3179-assignment2/refs/heads/main/australia-states.json",
        format: { type: "topojson", feature: "STE_2021_AUST_GDA2020" },
      },
      mark: {
        type: "geoshape",
        fill: BG3,
        stroke: BORDER,
        strokeWidth: 1,
      },
    },
    {
      data: { values: MONITORING_LOCATIONS },
      transform: [
        {
          calculate:
            "datum.status === 'Critically Endangered' ? 80 : datum.status === 'Endangered' ? 50 : 30",
          as: "pt_size",
        },
      ],
      mark: {
        type: "circle",
        opacity: 0.7,
        stroke: BG,
        strokeWidth: 0.5,
      },
      encoding: {
        longitude: { field: "lon", type: "quantitative" },
        latitude: { field: "lat", type: "quantitative" },
        color: {
          field: "status",
          type: "nominal",
          scale: {
            domain: ["Critically Endangered", "Endangered", "Vulnerable"],
            range: STATUS_RANGE_THREE,
          },
          legend: {
            orient: "bottom-left",
            title: "Threat Status",
            symbolSize: 80,
          },
        },
        size: {
          field: "pt_size",
          type: "quantitative",
          legend: null,
          scale: { range: [30, 80] },
        },
        tooltip: [
          { field: "common_name", title: "Species" },
          { field: "status", title: "Threat Status" },
          { field: "state", title: "State" },
          { field: "group", title: "Group" },
        ],
      },
    },
  ],
};
vegaEmbed("#map2", map2, embedOptions);

const chart6 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 320,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: BIRD_TREND },
  layer: [
    {
      mark: {
        type: "line",
        point: false,
        interpolate: "monotone",
        strokeWidth: 2.5,
      },
      encoding: {
        x: {
          field: "year",
          type: "quantitative",
          title: "Year",
          axis: { format: "d", grid: false },
        },
        y: {
          field: "index",
          type: "quantitative",
          title: "Population Index (1990 = 100)",
          axis: { grid: true, gridColor: GRID },
        },
        color: {
          field: "group",
          type: "nominal",
          scale: {
            domain: ["Critically Endangered", "Endangered", "Vulnerable"],
            range: STATUS_RANGE_THREE,
          },
          legend: {
            orient: "top",
            anchor: "middle",
            direction: "horizontal",
            columns: 3,
            title: null,
          },
        },
      },
    },
    {
      mark: {
        type: "rule",
        strokeDash: [4, 3],
        color: TEXT3,
        opacity: 0.5,
      },
      encoding: { y: { datum: 100 } },
    },
    {
      data: { values: [{ y: 100, label: "1990 Baseline" }] },
      mark: {
        type: "text",
        align: "right",
        dx: -4,
        dy: -6,
        fontSize: 11,
        color: TEXT3,
      },
      encoding: {
        x: { datum: 2022 },
        y: { field: "y", type: "quantitative" },
        text: { field: "label" },
      },
    },
  ],
  resolve: { scale: { y: "shared" } },
};
vegaEmbed("#chart6", chart6, embedOptions);

const stateAbbrMap = {
  "Australian Capital Territory": "ACT",
  "New South Wales": "NSW",
  "Northern Territory": "NT",
  Queensland: "QLD",
  "South Australia": "SA",
  Tasmania: "TAS",
  Victoria: "VIC",
  "Western Australia": "WA",
};
const BIRDS_STATE_ABBR = BIRDS_STATE.map((d) => ({
  ...d,
  state_abbr: stateAbbrMap[d.State] || d.State,
}));

const chart7 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 320,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: BIRDS_STATE_ABBR },
  mark: { type: "bar", cornerRadiusTopLeft: 2, cornerRadiusTopRight: 2 },
  encoding: {
    x: {
      field: "state_abbr",
      type: "nominal",
      title: null,
      axis: { labelAngle: -30 },
    },
    xOffset: {
      field: "EPBCStatus",
      type: "nominal",
      sort: ["Critically Endangered", "Endangered", "Vulnerable"],
    },
    y: {
      field: "count",
      type: "quantitative",
      title: "Species",
      axis: { grid: true, gridColor: GRID },
    },
    color: {
      field: "EPBCStatus",
      type: "nominal",
      scale: {
        domain: ["Critically Endangered", "Endangered", "Vulnerable"],
        range: STATUS_RANGE_THREE,
      },
      legend: {
        orient: "top",
        anchor: "middle",
        direction: "horizontal",
        columns: 3,
        title: null,
      },
    },
    tooltip: [
      { field: "State", title: "State" },
      { field: "EPBCStatus", title: "Status" },
      { field: "count", title: "Bird Species" },
    ],
  },
};
vegaEmbed("#chart7", chart7, embedOptions);

const chart8 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 380,
  autosize: { type: "fit-x", contains: "padding" },
  config: baseConfig,
  data: { values: TOP_BIRDS },
  layer: [
    {
      mark: { type: "rule", strokeWidth: 1.5, opacity: 0.5 },
      encoding: {
        y: {
          field: "CommonName",
          type: "nominal",
          sort: { field: "sites", order: "descending" },
          title: null,
        },
        x: { datum: 0 },
        x2: { field: "sites" },
        color: {
          field: "status",
          type: "nominal",
          scale: {
            domain: ["Critically Endangered", "Endangered", "Vulnerable"],
            range: STATUS_RANGE_THREE,
          },
        },
      },
    },
    {
      mark: { type: "point", filled: true, size: 100 },
      encoding: {
        y: {
          field: "CommonName",
          type: "nominal",
          sort: { field: "sites", order: "descending" },
          title: null,
          axis: { labelFontSize: 11 },
        },
        x: {
          field: "sites",
          type: "quantitative",
          title: "Monitoring Sites",
          axis: { grid: true, gridColor: GRID },
        },
        color: {
          field: "status",
          type: "nominal",
          scale: {
            domain: ["Critically Endangered", "Endangered", "Vulnerable"],
            range: STATUS_RANGE_THREE,
          },
          legend: { orient: "bottom-right", title: "EPBC Status" },
        },
        tooltip: [
          { field: "CommonName", title: "Species" },
          { field: "status", title: "Status" },
          { field: "sites", title: "Monitoring Sites" },
        ],
      },
    },
  ],
};
vegaEmbed("#chart8", chart8, embedOptions);

const map3 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 420,
  config: baseConfig,
  projection: { type: "mercator", center: [133, -28], scale: 650 },
  layer: [
    {
      data: {
        url: "https://raw.githubusercontent.com/SohamDarekar/fit3179-assignment2/refs/heads/main/australia-states.json",
        format: { type: "topojson", feature: "STE_2021_AUST_GDA2020" },
      },
      mark: {
        type: "geoshape",
        fill: BG3,
        stroke: BORDER,
        strokeWidth: 1,
      },
    },
    {
      data: { values: MONITORING_LOCATIONS },
      params: [
        {
          name: "statusSel",
          select: { type: "point", fields: ["status"] },
          bind: "legend",
        },
      ],
      transform: [
        {
          calculate:
            "datum.status === 'Critically Endangered' ? 100 : datum.status === 'Endangered' ? 55 : 32",
          as: "pt_size",
        },
      ],
      mark: { type: "circle", stroke: BG, strokeWidth: 0.5 },
      encoding: {
        longitude: { field: "lon", type: "quantitative" },
        latitude: { field: "lat", type: "quantitative" },
        color: {
          field: "status",
          type: "nominal",
          scale: {
            domain: ["Critically Endangered", "Endangered", "Vulnerable"],
            range: STATUS_RANGE_THREE,
          },
          legend: {
            orient: "bottom-left",
            title: "Click to filter by status",
            titleFontSize: 10,
          },
        },
        opacity: {
          condition: { param: "statusSel", value: 0.85 },
          value: 0.1,
        },
        size: {
          field: "pt_size",
          type: "quantitative",
          legend: null,
          scale: { range: [32, 100] },
        },
        tooltip: [
          { field: "common_name", title: "Species" },
          { field: "status", title: "Threat Status" },
          { field: "state", title: "State" },
          { field: "group", title: "Group" },
        ],
      },
    },
  ],
};
vegaEmbed("#map3", map3, embedOptions);

const chart9 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 360,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: TOP_FAM },
  mark: { type: "bar", cornerRadius: 2 },
  encoding: {
    y: {
      field: "family",
      type: "nominal",
      title: null,
      sort: { field: "count", op: "sum", order: "descending" },
      axis: { labelFontSize: 11, labelFont: "Source Sans 3, sans-serif" },
    },
    x: {
      field: "count",
      type: "quantitative",
      title: "Species Count",
      axis: { grid: true, gridColor: GRID },
    },
    color: {
      field: "status",
      type: "nominal",
      scale: {
        domain: ["Critically Endangered", "Endangered", "Vulnerable"],
        range: STATUS_RANGE_THREE,
      },
      legend: {
        orient: "bottom",
        anchor: "middle",
        direction: "horizontal",
        columns: 3,
        title: null,
      },
    },
    order: {
      field: "status",
      sort: ["Critically Endangered", "Endangered", "Vulnerable"],
    },
    tooltip: [
      { field: "family", title: "Family" },
      { field: "status", title: "Status" },
      { field: "count", title: "Species" },
    ],
  },
};
vegaEmbed("#chart9", chart9, embedOptions);

const PLANT_STATUS = [
  { status: "Critically Endangered", count: 306 },
  { status: "Endangered", count: 610 },
  { status: "Vulnerable", count: 563 },
  { status: "Extinct", count: 35 },
];

const chart10 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 340,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: PLANT_STATUS },
  layer: [
    {
      mark: {
        type: "arc",
        outerRadius: 132,
        innerRadius: 66,
        stroke: BG,
        strokeWidth: 2,
      },
      encoding: {
        theta: { field: "count", type: "quantitative", stack: true },
        color: {
          field: "status",
          type: "nominal",
          scale: {
            domain: [
              "Critically Endangered",
              "Endangered",
              "Vulnerable",
              "Extinct",
            ],
            range: STATUS_RANGE,
          },
          legend: {
            orient: "bottom",
            anchor: "middle",
            direction: "horizontal",
            columns: 4,
            title: null,
          },
        },
        tooltip: [
          { field: "status", title: "Status" },
          { field: "count", title: "Plant Species", format: "," },
        ],
      },
    },
    {
      mark: {
        type: "text",
        fontSize: 26,
        fontWeight: 700,
        font: "Playfair Display, serif",
        color: TEXT,
      },
      encoding: {
        text: { value: "1,514" },
      },
    },
    {
      mark: { type: "text", fontSize: 12, dy: 20, color: TEXT3 },
      encoding: {
        text: { value: "plant species" },
      },
    },
  ],
};
vegaEmbed("#chart10", chart10, embedOptions);

const chart12 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 340,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: HOTSPOT.filter((d) => d.state !== "ACT") },
  layer: [
    {
      mark: { type: "circle", opacity: 0.85 },
      encoding: {
        x: {
          field: "total",
          type: "quantitative",
          title: "Total Threatened Species",
          axis: { grid: true, gridColor: GRID },
        },
        y: {
          field: "endemic",
          type: "quantitative",
          title: "Single-State Endemics",
          axis: { grid: true, gridColor: GRID },
        },
        size: {
          field: "pct_endemic",
          type: "quantitative",
          title: "% Endemic",
          scale: { range: [60, 500] },
          legend: {
            orient: "bottom",
            anchor: "middle",
            direction: "horizontal",
            titleFontSize: 12,
          },
        },
        color: { value: STATUS_COLORS.Endangered },
        tooltip: [
          { field: "state", title: "State" },
          { field: "total", title: "Total Threatened" },
          { field: "endemic", title: "Single-State Endemics" },
          { field: "pct_endemic", title: "% Endemic", format: ".1f" },
        ],
      },
    },
    {
      mark: {
        type: "text",
        dy: -14,
        fontSize: 12,
        color: TEXT,
        fontWeight: 600,
      },
      encoding: {
        x: { field: "total", type: "quantitative" },
        y: { field: "endemic", type: "quantitative" },
        text: { field: "state" },
      },
    },
  ],
};
vegaEmbed("#chart12", chart12, embedOptions);

const STATES_ORDER = ["ACT", "NSW", "QLD", "SA", "TAS", "VIC", "WA", "NT"];
const chart13 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 300,
  autosize: { type: "fit-x", contains: "padding" },
  config: {
    ...baseConfig,
    axis: {
      ...baseConfig.axis,
      labelFontSize: 12,
      titleFontSize: 13,
    },
    legend: {
      ...baseConfig.legend,
      labelFontSize: 13,
      symbolSize: 140,
    },
  },
  data: { values: CO_OCCUR },
  mark: { type: "circle" },
  encoding: {
    x: {
      field: "state1",
      type: "nominal",
      sort: STATES_ORDER,
      title: null,
      axis: { labelAngle: -30 },
    },
    y: {
      field: "state2",
      type: "nominal",
      sort: STATES_ORDER,
      title: null,
    },
    size: {
      field: "shared",
      type: "quantitative",
      scale: { range: [20, 1200] },
      title: "Shared species",
      legend: {
        orient: "right",
        titleFontSize: 12,
        labelFontSize: 12,
      },
    },
    color: {
      field: "shared",
      type: "quantitative",
      scale: { range: ["#283341", "#5e7380", STATUS_COLORS.Endangered] },
      legend: null,
    },
    tooltip: [
      { field: "state1", title: "State A" },
      { field: "state2", title: "State B" },
      { field: "shared", title: "Shared Species", format: "," },
    ],
  },
};
vegaEmbed("#chart13", chart13, embedOptions);

const MAMMAL_TREND = POP_TREND.filter((d) => d.group === "Mammals");
const chart14 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 280,
  config: baseConfig,
  data: { values: MAMMAL_TREND },
  layer: [
    {
      mark: {
        type: "area",
        line: { color: MAMMAL_COLOR, strokeWidth: 2.5 },
        color: MAMMAL_COLOR,
        opacity: 0.2,
        interpolate: "monotone",
      },
      encoding: {
        x: {
          field: "year",
          type: "quantitative",
          title: "Year",
          axis: { format: "d", grid: false },
        },
        y: {
          field: "mean_count",
          type: "quantitative",
          title: "Average Abundance Index",
          axis: { grid: true, gridColor: GRID },
        },
        tooltip: [
          { field: "year", type: "quantitative", title: "Year" },
          { field: "mean_count", title: "Avg Index", format: ".1f" },
        ],
      },
    },
    {
      mark: {
        type: "point",
        filled: true,
        color: MAMMAL_COLOR,
        size: 60,
        opacity: 0.9,
      },
      encoding: {
        x: { field: "year", type: "quantitative" },
        y: { field: "mean_count", type: "quantitative" },
      },
    },
  ],
};
vegaEmbed("#chart14", chart14, embedOptions);

const chart15 = {
  $schema: "https://vega.github.io/schema/vega-lite/v5.json",
  width: "container",
  height: 320,
  config: baseConfig,
  data: { values: POP_TREND },
  mark: {
    type: "line",
    point: true,
    interpolate: "monotone",
    strokeWidth: 2.5,
  },
  encoding: {
    x: {
      field: "year",
      type: "quantitative",
      title: "Year",
      axis: { format: "d", grid: false },
    },
    y: {
      field: "mean_count",
      type: "quantitative",
      title: "Average Population Index",
      axis: { grid: true, gridColor: GRID },
    },
    color: {
      field: "group",
      type: "nominal",
      scale: {
        domain: ["Birds", "Mammals", "Amphibians"],
        range: [STATUS_COLORS.Endangered, MAMMAL_COLOR, STATUS_COLORS.Extinct],
      },
      legend: { orient: "top-right", title: null },
    },
    tooltip: [
      { field: "group", title: "Group" },
      { field: "year", title: "Year" },
      { field: "mean_count", title: "Avg Index", format: ".1f" },
    ],
  },
};
vegaEmbed("#chart15", chart15, embedOptions);
